# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 3
      docker:
        # 指定开发环境镜像，可以是任意可访问的镜像
        image: guergeiro/pnpm:20-10-alpine
        volumes:
          # 使用缓存，同时更新
          - /root/.npm:copy-on-write
          - /root/.local/share/pnpm/store/v10:copy-on-write
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: config
          script:
            - pnpm config set registry https://registry.npmmirror.com
            